---
- name: install htpc software
  apt: name={{item}} state=installed
  with_items:
    - retroarch
    - kodi
    - nethack-console
    - crawl
    - crawl-tiles
    - angband
    - kobodeluxe
- name: setup htpc user
  user:
    name: htpc
    state: present
    home: /home/htpc
    append: yes
    generate_ssh_key: yes
    shell: /bin/zsh
- name: authorize your local SSH public key for user htpc
  authorized_key:
    user: htpc
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
# FIXME: This part doesn't seem to work?
- name: set htpc as autologin user
  include_role:
    name: gantsign.lightdm
  vars:
    lightdm_autologin_user: htpc
    lightdm_autologin_timeout: 5
