# Assumes you've run tinkerboard-init

- hosts: tinkerboard
  become: yes
  tasks:
    # Keyboard setup
    - name: set up colemak keyboard
      include_role:
        name: gantsign.keyboard
      vars:
        keyboard_model: pc105
        keyboard_layout: us
        keyboard_variant: colemak
        keyboard_options: ctrl(swapcaps)
    # General softare
    - name: install common software
      apt: name={{ item }} state=installed
      with_items:
        - sudo
        - vim
        - git
        - tmux
        - mosh
        - p7zip-full
        - youtube-dl
        - imagemagick
        - optipng
        - tmpreaper
    - name: install desktop environment
      apt: name={{item}} state=installed
      with_items:
        - lightdm
        - i3
        - i3status
        - suckless-tools
    # HTPC setup
    - name: install htpc software
      apt: name={{item}} state=installed
      with_items:
        - kodi
        - retroarch
    - name: setup htpc user
      user:
        name: htpc
        state: present
        home: /home/htpc
        append: yes
        generate_ssh_key: yes
        shell: /bin/zsh
    - name: authorize your local SSH public key for user htpc
      authorized_key:
        user: htpc
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
    - name: set htpc as autologin user
      include_role:
        name: gantsign.lightdm
      vars:
        lightdm_autologin_user: htpc
        lightdm_autologin_timeout: 5
