# Set up a proper user on a Tinkerboard with a fresh TinkerOS image.
#
# The script will generate a user that's the same as your current host
# username. If you want to override this, set 'main_user' in extra-vars
#
# Before running this script, find out the MAC addresses of the eth and wifi
# network interfaces on the board and configure your router to assign fixed IP
# addresses to them in DHCP. That way the board can work as a server.

# This is a separate playbook because it uses the default linaro user and
# password, which you should disable soon afterwards.

- hosts: tinkerboard
  become: yes
  vars:
    new_user: "{{ main_user | default(lookup('env', 'USER')) }}"
    ansible_ssh_user: linaro
    ansible_ssh_pass: linaro
  tasks:
    - name: set hostname to '{{ inventory_hostname }}'
      hostname:
        name: "{{ inventory_hostname }}"
    - lineinfile:
        dest: /etc/hosts
        state: present
        line: '127.0.1.1       {{ inventory_hostname }}'

    # XXX: The wheel group bit should be moved to some reusable place
    - name: create 'wheel' group
      group:
        name=wheel
        state=present
    - name: allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: install zsh
      apt: name=zsh state=installed
    - name: setup user '{{ new_user }}'
      user:
        name: "{{ new_user }}"
        state: present
        home: /home/{{ new_user }}
        groups: wheel
        append: yes
        generate_ssh_key: yes
        shell: /bin/zsh
    - name: setup /home/{{ new_user }}
      file:
        path: /home/{{ new_user }}
        state: directory
        owner: "{{ new_user }}"
    - name: authorize your local SSH public key for '{{ new_user }}'
      authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
