- name: Set up Colemak keyboard
  include_role:
    name: gantsign.keyboard
  vars:
    keyboard_model: pc105
    keyboard_layout: us
    keyboard_variant: colemak
    keyboard_options: ctrl(swapcaps)
