- name: set up colemak keyboard
  include_role:
    name: gantsign.keyboard
  vars:
    keyboard_model: pc105
    keyboard_layout: us
    keyboard_variant: colemak
    keyboard_options: ctrl(swapcaps)

- name: Make sure we have a 'wheel' group
  group:
    name=wheel
    state=present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set time zone to Europe/Helsinki
  timezone:
    name: Europe/Helsinki
