# Make dotfiles read-only when deployed because the workflow is to only edit
# them through Ansible.
- name: create dotfile directories
  file: path=/home/{{ user }}/{{ item }} state=directory owner={{ user }}
  with_items:
    - .config/i3
    - .config/i3status
    - .vim/autoload
  tags:
    - user

- name: install dotfiles
  copy: src={{ item }} dest=/home/{{ user }}/{{ item }} mode=0400 owner={{ user }}
  with_items:
    - .zshrc
    - .vimrc
    - .config/i3/config
    - .config/i3status/config
  tags:
    - user

- name: download vim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ user }}/.vim/autoload/plug.vim
    owner: "{{ user }}"
  tags:
    - user

# FIXME: Get this working
#- name: install vim plugins
#  command: vim +PlugInstall +qall
#  chdir: /home/{{ user }}
#  become: true
#  become_user: "{{ user }}"
