# Make dotfiles read-only when deployed because the workflow is to only edit
# them through Ansible.
- name: create dotfile directories
  become_user: "{{ user }}"
  file: path=/home/{{ user }}/{{ item }} state=directory owner={{ user }}
  with_items:
    - .config/i3
    - .config/i3status
    - .vim/autoload
    - .vim/swap
    - .vim/backup
  tags:
    - dotfiles

- name: install dotfiles
  become_user: "{{ user }}"
  copy: src={{ item }} dest=/home/{{ user }}/{{ item }} mode=0400 owner={{ user }}
  with_items:
    - .zshrc
    - .vimrc
    - .config/i3/config
    - .config/i3status/config
    - .Xresources
    - .xsession
  tags:
    - dotfiles

# TODO: Run xrdb .Xresources whenever it's changed

- name: download vim plugin manager
  become_user: "{{ user }}"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ user }}/.vim/autoload/plug.vim
    owner: "{{ user }}"

# FIXME: This runs a pretty slow vim command every time it's hit.
# Just do it manually for now.
#
#- name: install vim plugins
#  command: vim +PlugInstall +qall
#  become: true
#  become_user: "{{ user }}"
