- name: update the apt cache
  apt: update_cache=Yes
- name: install common software
  apt: name={{item}} state=installed
  with_items:
    - sudo
    - vim
    - git
    - tmux
    - mosh
    - p7zip-full
    - youtube-dl
    - imagemagick
    - optipng
    - zsh
    - tmpreaper
- name: install desktop environment
  apt: name={{item}} state=installed
  with_items:
    - i3
    - lightdm
    - i3status
    - suckless-tools
    - rxvt-unicode
    - i3lock
    - redshift
- name: Set preferred terminal to urxvt
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvt
- name: install desktop software
  apt: name={{item}} state=installed
  with_items:
    - chromium
    - mupdf
    - djview4
    - mcomix
    - feh
    - vim-gtk3
    - grafx2
    - mplayer
    - x11-xserver-utils
